--30/07/2025  
--@IvanReis
--Refatorada para performance por Gemini Code Assist

-- HSF - PAINEL FLORENCE - CENSO
WITH
latest_mews AS (
  SELECT
    NR_ATENDIMENTO,
    QT_PONTUACAO,
    CASE WHEN QT_PONTUACAO BETWEEN 0 AND 4 THEN 'BAIXO' WHEN QT_PONTUACAO BETWEEN 5 AND 6 THEN 'MEDIO' WHEN QT_PONTUACAO BETWEEN 7 AND 12 THEN 'ALTO' ELSE NULL END AS DS_MEWS,
    ROW_NUMBER() OVER(PARTITION BY NR_ATENDIMENTO ORDER BY DT_AVALIACAO DESC) as rn
  FROM ESCALA_MEWS WHERE IE_SITUACAO = 'A'
),
latest_braden AS (
  SELECT
    NR_ATENDIMENTO,
    QT_PONTO,
    INITCAP(OBTER_RESULTADO_BRADEN(QT_PONTO)) as DS_BRADEN,
    ROW_NUMBER() OVER(PARTITION BY NR_ATENDIMENTO ORDER BY DT_AVALIACAO DESC) as rn -- ATENÇÃO: Verifique se DT_AVALIACAO é a coluna correta
  FROM ATEND_ESCALA_BRADEN WHERE IE_SITUACAO = 'A'
),
latest_morse AS (
  SELECT
    NR_ATENDIMENTO,
    QT_PONTUACAO,
    INITCAP(OBTER_DESC_ESCALA_MORSE(QT_PONTUACAO)) as DS_MORSE,
    ROW_NUMBER() OVER(PARTITION BY NR_ATENDIMENTO ORDER BY DT_AVALIACAO DESC) as rn -- ATENÇÃO: Verifique se DT_AVALIACAO é a coluna correta
  FROM ESCALA_MORSE WHERE IE_SITUACAO = 'A'
),
latest_saps3 AS (
  SELECT
    NR_ATENDIMENTO,
    QT_PONTUACAO,
    QT_PONTUACAO || ' / ' || PR_RISCO || '%' as DS_SAPSIII,
    ROW_NUMBER() OVER(PARTITION BY NR_ATENDIMENTO ORDER BY DT_AVALIACAO DESC) as rn -- ATENÇÃO: Verifique se DT_AVALIACAO é a coluna correta
  FROM ESCALA_SAPS3 WHERE IE_SITUACAO = 'A'
),
latest_rass AS (
  SELECT
    NR_ATENDIMENTO,
    IE_RASS,
    OBTER_VALOR_DOMINIO(2088, IE_RASS) AS DS_RASS,
    ROW_NUMBER() OVER(PARTITION BY NR_ATENDIMENTO ORDER BY DT_AVALIACAO DESC) as rn -- ATENÇÃO: Verifique se DT_AVALIACAO é a coluna correta
  FROM ESCALA_RICHMOND WHERE OBTER_SE_REG_LIB_ATENCAO(OBTER_PESSOA_ATENDIMENTO(NR_ATENDIMENTO, 'C'),CD_PROFISSIONAL,IE_NIVEL_ATENCAO,NM_USUARIO,374) = 'S'
),
latest_fugulin AS (
  SELECT
    GCAA.NR_ATENDIMENTO,
    GCAG.DS_GRADACAO AS CD_FUGULIN,
    DECODE(GCAG.DS_GRADACAO, 'CM','Cuidados Mínimos', 'CI','Cuidados Intermediários', 'AD','Alta Dependência', 'SI','Cuidados Semi Intensivos', 'I','Cuidados Intensivos', GCAG.DS_GRADACAO) AS FUGULIN,
    ROW_NUMBER() OVER(PARTITION BY GCAA.NR_ATENDIMENTO ORDER BY GCAA.DT_AVALIACAO DESC) as rn
  FROM GCA_ATENDIMENTO GCAA
  JOIN GCA_GRADACAO GCAG ON GCAG.NR_SEQUENCIA = GCAA.NR_SEQ_GRADACAO
  WHERE GCAA.IE_SITUACAO = 'A'
),
latest_martins AS (
  SELECT
    NR_ATENDIMENTO,
    SUBSTR(OBTER_DESC_RESUL_SCORE_FLEX_2(QT_PONTOS, NR_SEQ_ESCALA), 1, 255) AS MARTINS,
    ROW_NUMBER() OVER(PARTITION BY NR_ATENDIMENTO ORDER BY DT_AVALIACAO DESC) as rn
  FROM ESCALA_EIF_II
  WHERE IE_SITUACAO = 'A' AND DT_LIBERACAO IS NOT NULL
),
latest_glasgow AS (
  SELECT
    NR_ATENDIMENTO,
    QT_GLASGOW,
    OBTER_RESULTADO_GLASGOW(QT_GLASGOW) AS DS_GLASGOW,
    ROW_NUMBER() OVER(PARTITION BY NR_ATENDIMENTO ORDER BY DT_AVALIACAO DESC) as rn
  FROM ATEND_ESCALA_INDICE
  WHERE OBTER_SE_REG_LIB_ATENCAO(OBTER_PESSOA_ATENDIMENTO(NR_ATENDIMENTO,'C'), CD_PESSOA_FISICA, IE_NIVEL_ATENCAO, NM_USUARIO, 374) = 'S'
)
SELECT DISTINCT
    --A.DATA_REF DATA_REFERENCIA,
    --A.SITUACAO_LEITO,
    --A.STATUS_LEITO_DESCR STATUS_LEITO,
    A.CD_SETOR_ATENDIMENTO,
    A.SEOTR_ATENDIMENTO SETOR,
    A.LEITO ||' '|| A.COMPLEMENTO AS LEITO,
    A.NR_ATENDIMENTO,
    OBTER_NOME_PACIENTE(A.NR_ATENDIMENTO) AS PACIENTE,
    mews.QT_PONTUACAO AS CD_MEWS,
    mews.DS_MEWS AS MEWS,
    braden.QT_PONTO AS CD_BRADEN,
    braden.DS_BRADEN AS BRADEN,
    morse.QT_PONTUACAO AS CD_MORSE,
    morse.DS_MORSE AS MORSE,
    saps3.QT_PONTUACAO AS CD_SAPSIII,
    saps3.DS_SAPSIII AS SAP3,
    rass.IE_RASS AS CD_RASS,
    rass.DS_RASS AS RASS,
    fugulin.CD_FUGULIN,
    fugulin.FUGULIN,
    martins.MARTINS,
    glasgow.QT_GLASGOW AS CD_GLASGOW,
    glasgow.DS_GLASGOW AS GLASGOW
FROM PH_OCUPACAO_RETROATIVA A
LEFT JOIN latest_mews mews ON A.NR_ATENDIMENTO = mews.NR_ATENDIMENTO AND mews.rn = 1
LEFT JOIN latest_braden braden ON A.NR_ATENDIMENTO = braden.NR_ATENDIMENTO AND braden.rn = 1
LEFT JOIN latest_morse morse ON A.NR_ATENDIMENTO = morse.NR_ATENDIMENTO AND morse.rn = 1
LEFT JOIN latest_saps3 saps3 ON A.NR_ATENDIMENTO = saps3.NR_ATENDIMENTO AND saps3.rn = 1
LEFT JOIN latest_rass rass ON A.NR_ATENDIMENTO = rass.NR_ATENDIMENTO AND rass.rn = 1
LEFT JOIN latest_fugulin fugulin ON A.NR_ATENDIMENTO = fugulin.NR_ATENDIMENTO AND fugulin.rn = 1
LEFT JOIN latest_martins martins ON A.NR_ATENDIMENTO = martins.NR_ATENDIMENTO AND martins.rn = 1
LEFT JOIN latest_glasgow glasgow ON A.NR_ATENDIMENTO = glasgow.NR_ATENDIMENTO AND glasgow.rn = 1
WHERE
    A.SITUACAO_LEITO = 'A'
    AND A.STATUS_LEITO = 'P'
    -- Otimização: Evita o TRUNC() na coluna para permitir o uso de índices.
    AND A.DATA_REF >= TO_DATE(:DATA_INICIAL, 'dd/mm/yyyy') 
    AND A.DATA_REF < TO_DATE(:DATA_FINAL, 'dd/mm/yyyy') + 1
    AND ((A.CD_SETOR_ATENDIMENTO = :CD_SETOR_P) OR (:CD_SETOR_P = '0'))
