SELECT DISTINCT 
    ATP.CD_SETOR_ATENDIMENTO, 
    ATP.NM_UNIDADE_BASICA,
    PP.NR_PRESCRICAO, 
    EL.NM_EXAME,
    ATP.NR_ATENDIMENTO,
    SUBSTR(obter_nome_pf(ATP.CD_PESSOA_FISICA), 1, 1) || 
    SUBSTR(ABREVIA_NOME(obter_nome_pf(ATP.CD_PESSOA_FISICA), 'A'), 
    INSTR(ABREVIA_NOME(obter_nome_pf(ATP.CD_PESSOA_FISICA), 'A'), ' ')) NM_PACIENTE,
    DECODE( 
        PP.IE_STATUS_ATEND,
        10,'Pendente de Coleta',
        20,'Material Coletado',
        25,'Triagem / Área Técnica',
        30,'Digitação do Resultado',
        35,'Aprovação do Resultado',
        45,'Entrega do Exame', 'Outro / Indefinido'
        ) STATUS_ATUAL,
    CASE WHEN(
                TRUNC(
                        (
                            (
                                NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '35', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE) 
                                - 
                                NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '20', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE)
                            )*24*60
                        ) / (120)*100
                    )
            ) < 100 
    THEN 'Dentro do prazo'
    ELSE 'Atrasado'
    END AS APRAZO,
    TRUNC(
            (
                    (
                        NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '35', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE) 
                        - 
                        NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '20', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE)
                    )*24*60) / (120)*100
        ) AS t_e_percent,
    abrevia_nome_pf(Obter_Dados_Usuario_Opcao(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '10', 'U'),'C'),'A') nm_usuario_libera,
    OBTER_DIF_DATA(NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '10', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE), 
    NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '20', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE), 'S') t_A,
    OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '20', 'D') dt_col,
    OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '20', 'U') NM_USUA,
    OBTER_DIF_DATA(NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '20', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE), 
    NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '25', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE), 'S') t_B,
    OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '25', 'D') dt_distribui,
    OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '25', 'U') DISTRIBUI,
    OBTER_DIF_DATA(NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '25', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE), 
    NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '30', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE), 'S') t_C,
    OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '30', 'D') dt_digita,
    OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '30', 'U') DIGITA,
    OBTER_DIF_DATA(NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '30', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE), 
    NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '35', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE), 'S') t_D,
    OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '35', 'D') dt_apr,
    OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '35', 'U') APROVA,
    OBTER_DIF_DATA(NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '20', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE), 
    NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '35', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE), 'S') t_E
FROM PRESCR_MEDICA PRM
INNER JOIN ATENDIMENTO_PACIENTE_V ATP ON ATP.NR_ATENDIMENTO = PRM.NR_ATENDIMENTO
INNER JOIN PRESCR_PROCEDIMENTO PP ON PP.NR_PRESCRICAO = PRM.NR_PRESCRICAO
INNER JOIN EXAME_LABORATORIO EL ON EL.NR_SEQ_EXAME = PP.NR_SEQ_EXAME
WHERE TRUNC(PRM.DT_PRESCRICAO)  BETWEEN SYSDATE -3 AND SYSDATE  
AND (( ATP.CD_SETOR_ATENDIMENTO = :cd_setor))
--AND 
--(CASE WHEN(TRUNC(((NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '35', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE) - NVL(TO_DATE(OBTER_LAB_EXECUCAO_ETAPA(PP.NR_PRESCRICAO, PP.NR_SEQUENCIA, '20', 'D'), 'DD/MM/YYYY HH24:MI:SS'), SYSDATE))*24*60)/(120)*100))< 100 THEN 'Dentro do prazo'
--ELSE 'Atrasado' END ) = 'Dentro do prazo'
ORDER BY 6,8,12      
