-- query_hemogramas.sql

SELECT 
    RL.NR_PRESCRICAO, 
    SUBSTR(obter_nome_pf(AP.CD_PESSOA_FISICA), 1, 1) || 
    SUBSTR(ABREVIA_NOME(obter_nome_pf(AP.CD_PESSOA_FISICA), 'A'), 
    INSTR(ABREVIA_NOME(obter_nome_pf(AP.CD_PESSOA_FISICA), 'A'), ' '))  AS NM_PACIENTE,
    RL.DS_RESULTADO DS_RESULTADO_RTF,   
    RL.DT_COLETA DT_EXAME
FROM RESULT_LABORATORIO_V RL
LEFT JOIN PRESCR_PROCEDIMENTO PP ON PP.NR_PRESCRICAO = RL.NR_PRESCRICAO
LEFT JOIN PRESCR_MEDICA PM ON PP.NR_PRESCRICAO = PM.NR_PRESCRICAO
LEFT JOIN ATENDIMENTO_PACIENTE_V AP ON AP.NR_ATENDIMENTO = PM.NR_ATENDIMENTO
WHERE TRUNC(RL.DT_COLETA) >= TO_DATE(:data_inicial, 'YYYY-MM-DD')
    AND TRUNC(RL.DT_COLETA) <= TO_DATE(:data_final, 'YYYY-MM-DD')
    AND RL.DS_RESULTADO IS NOT NULL
ORDER BY
    RL.DT_COLETA DESC
