-- Refatorado: 2025-04-15
-- @IvanReis
-- Substituição de subconsultas correlacionadas por CTEs com ROW_NUMBER().
-- Objetivo: eliminar O(n*escalas) subqueries; cada escala é executada uma única vez
-- e filtrada apenas para os atendimentos relevantes do período/setor.

WITH

-- 1. Pré-filtra os atendimentos do período e setor para reduzir o escopo das CTEs
CTE_ATENDIMENTOS AS (
    SELECT DISTINCT APV.NR_ATENDIMENTO
    FROM ATENDIMENTO_PACIENTE_V APV
    JOIN PH_OCUPACAO_RETROATIVA POR
        ON POR.NR_ATENDIMENTO = APV.NR_ATENDIMENTO
    WHERE POR.SITUACAO_LEITO = 'A'
      AND POR.STATUS_LEITO   = 'P'
      AND POR.DATA_REF >= TO_DATE(:DATA_INICIAL, 'dd/mm/yyyy')
      AND POR.DATA_REF  < TO_DATE(:DATA_FINAL,   'dd/mm/yyyy') + 1
    /*{{FILTER_SETOR}}*/
),

-- 2. MEWS — escala de alerta precoce (mais recente)
CTE_MEWS AS (
    SELECT
        EM.NR_ATENDIMENTO,
        EM.QT_PONTUACAO AS CD_MEWS,
        CASE
            WHEN EM.QT_PONTUACAO BETWEEN 0  AND 4  THEN 'BAIXO'
            WHEN EM.QT_PONTUACAO BETWEEN 5  AND 6  THEN 'MEDIO'
            WHEN EM.QT_PONTUACAO BETWEEN 7  AND 12 THEN 'ALTO'
            ELSE NULL
        END AS MEWS,
        ROW_NUMBER() OVER (
            PARTITION BY EM.NR_ATENDIMENTO
            ORDER BY EM.DT_AVALIACAO DESC
        ) AS RN
    FROM ESCALA_MEWS EM
    WHERE EM.IE_SITUACAO = 'A'
      AND EM.NR_ATENDIMENTO IN (SELECT NR_ATENDIMENTO FROM CTE_ATENDIMENTOS)
),

-- 3. BRADEN — risco de lesão por pressão (maior pontuação = menor risco)
CTE_BRADEN AS (
    SELECT
        AEB.NR_ATENDIMENTO,
        AEB.QT_PONTO AS CD_BRADEN,
        INITCAP(OBTER_RESULTADO_BRADEN(AEB.QT_PONTO)) AS BRADEN,
        ROW_NUMBER() OVER (
            PARTITION BY AEB.NR_ATENDIMENTO
            ORDER BY AEB.QT_PONTO DESC
        ) AS RN
    FROM ATEND_ESCALA_BRADEN AEB
    WHERE AEB.IE_SITUACAO = 'A'
      AND AEB.NR_ATENDIMENTO IN (SELECT NR_ATENDIMENTO FROM CTE_ATENDIMENTOS)
),

-- 4. MORSE — risco de queda
CTE_MORSE AS (
    SELECT
        EMM.NR_ATENDIMENTO,
        EMM.QT_PONTUACAO AS CD_MORSE,
        INITCAP(OBTER_DESC_ESCALA_MORSE(EMM.QT_PONTUACAO)) AS MORSE,
        ROW_NUMBER() OVER (
            PARTITION BY EMM.NR_ATENDIMENTO
            ORDER BY EMM.QT_PONTUACAO DESC
        ) AS RN
    FROM ESCALA_MORSE EMM
    WHERE EMM.IE_SITUACAO = 'A'
      AND EMM.NR_ATENDIMENTO IN (SELECT NR_ATENDIMENTO FROM CTE_ATENDIMENTOS)
),

-- 5. SAPS3 — score de mortalidade em UTI
CTE_SAPS3 AS (
    SELECT
        S3.NR_ATENDIMENTO,
        S3.QT_PONTUACAO AS CD_SAPSIII,
        S3.QT_PONTUACAO || ' / ' || S3.PR_RISCO || '%' AS SAP3,
        ROW_NUMBER() OVER (
            PARTITION BY S3.NR_ATENDIMENTO
            ORDER BY S3.QT_PONTUACAO DESC
        ) AS RN
    FROM ESCALA_SAPS3 S3
    WHERE S3.IE_SITUACAO = 'A'
      AND S3.NR_ATENDIMENTO IN (SELECT NR_ATENDIMENTO FROM CTE_ATENDIMENTOS)
),

-- 6. RASS — escala de sedação/agitação
CTE_RASS AS (
    SELECT
        ER.NR_ATENDIMENTO,
        ER.IE_RASS AS CD_RASS,
        OBTER_VALOR_DOMINIO(2088, ER.IE_RASS) AS RASS,
        ROW_NUMBER() OVER (
            PARTITION BY ER.NR_ATENDIMENTO
            ORDER BY ROWNUM
        ) AS RN
    FROM ESCALA_RICHMOND ER
    WHERE ER.NR_ATENDIMENTO IN (SELECT NR_ATENDIMENTO FROM CTE_ATENDIMENTOS)
      AND OBTER_SE_REG_LIB_ATENCAO(
              OBTER_PESSOA_ATENDIMENTO(ER.NR_ATENDIMENTO, 'C'),
              ER.CD_PROFISSIONAL,
              ER.IE_NIVEL_ATENCAO,
              ER.NM_USUARIO,
              374) = 'S'
),

-- 7. FUGULIN — classificação de dependência de cuidados
CTE_FUGULIN AS (
    SELECT
        GA.NR_ATENDIMENTO,
        GG.DS_GRADACAO AS CD_FUGULIN,
        DECODE(GG.DS_GRADACAO,
            'CM', 'Cuidados Mínimos',
            'CI', 'Cuidados Intermediários',
            'AD', 'Alta Dependência',
            'SI', 'Cuidados Semi Intensivos',
            'I',  'Cuidados Intensivos',
            GG.DS_GRADACAO
        ) AS FUGULIN,
        ROW_NUMBER() OVER (
            PARTITION BY GA.NR_ATENDIMENTO
            ORDER BY GA.DT_AVALIACAO DESC, GA.NR_SEQUENCIA DESC
        ) AS RN
    FROM GCA_ATENDIMENTO GA
    JOIN GCA_GRADACAO GG
        ON GG.NR_SEQUENCIA = GA.NR_SEQ_GRADACAO
    WHERE GA.IE_SITUACAO = 'A'
      AND GA.NR_ATENDIMENTO IN (SELECT NR_ATENDIMENTO FROM CTE_ATENDIMENTOS)
),

-- 8. MARTINS — escala de capacidade de auto-cuidado
--    Etapa 8a: desduplicar por (data, pontos, escala) antes do ROW_NUMBER
CTE_MARTINS_BASE AS (
    SELECT
        EEII.NR_ATENDIMENTO,
        EEII.DT_AVALIACAO,
        SUBSTR(OBTER_DESC_RESUL_SCORE_FLEX_2(EEII.QT_PONTOS, EEII.NR_SEQ_ESCALA), 1, 255) AS MARTINS
    FROM ESCALA_EIF_II EEII
    JOIN SCORE_AVALIACAO_RESULT SAR
        ON SAR.NR_SEQ_AVALIACAO = EEII.NR_SEQUENCIA
    JOIN MED_ITEM_AVALIAR MIA
        ON MIA.NR_SEQUENCIA = SAR.NR_SEQ_ITEM
    JOIN MED_TIPO_AVALIACAO MTA
        ON MTA.NR_SEQUENCIA = MIA.NR_SEQ_TIPO
    WHERE SAR.DS_RESULTADO  IS NOT NULL
      AND EEII.DT_LIBERACAO IS NOT NULL
      AND UPPER(MTA.DS_TIPO) LIKE '%MARTINS%'
      AND EEII.IE_SITUACAO = 'A'
      AND EEII.NR_ATENDIMENTO IN (SELECT NR_ATENDIMENTO FROM CTE_ATENDIMENTOS)
    GROUP BY EEII.NR_ATENDIMENTO, EEII.DT_AVALIACAO, EEII.QT_PONTOS, EEII.NR_SEQ_ESCALA
),
CTE_MARTINS AS (
    SELECT
        NR_ATENDIMENTO,
        MARTINS,
        ROW_NUMBER() OVER (
            PARTITION BY NR_ATENDIMENTO
            ORDER BY DT_AVALIACAO DESC
        ) AS RN
    FROM CTE_MARTINS_BASE
),

-- 9. GLASGOW — escala de coma
CTE_GLASGOW AS (
    SELECT
        AEI.NR_ATENDIMENTO,
        AEI.QT_GLASGOW AS CD_GLASGOW,
        OBTER_RESULTADO_GLASGOW(AEI.QT_GLASGOW) AS GLASGOW,
        ROW_NUMBER() OVER (
            PARTITION BY AEI.NR_ATENDIMENTO
            ORDER BY AEI.DT_AVALIACAO DESC
        ) AS RN
    FROM ATEND_ESCALA_INDICE AEI
    WHERE AEI.NR_ATENDIMENTO IN (SELECT NR_ATENDIMENTO FROM CTE_ATENDIMENTOS)
      AND OBTER_SE_REG_LIB_ATENCAO(
              OBTER_PESSOA_ATENDIMENTO(AEI.NR_ATENDIMENTO, 'C'),
              AEI.CD_PESSOA_FISICA,
              AEI.IE_NIVEL_ATENCAO,
              AEI.NM_USUARIO,
              374) = 'S'
)

-- =====================================================================
-- Query principal — une os dados de ocupação com as escalas via JOIN
-- =====================================================================
SELECT
    POR.CD_SETOR_ATENDIMENTO,
    OBTER_DESC_SETOR_ATEND(POR.CD_SETOR_ATENDIMENTO)   AS SETOR,
    POR.LEITO || ' ' || POR.COMPLEMENTO                AS LEITO,
    APV.NR_ATENDIMENTO,
    OBTER_NOME_PACIENTE(APV.NR_ATENDIMENTO)             AS PACIENTE,
    TO_CHAR(POR.DATA_REF, 'dd/mm/yy')                  AS ENTRADA,
    -- Escalas (NULL quando não avaliado)
    M.CD_MEWS,   M.MEWS,
    B.CD_BRADEN, B.BRADEN,
    MO.CD_MORSE, MO.MORSE,
    S.CD_SAPSIII, S.SAP3,
    R.CD_RASS,   R.RASS,
    F.CD_FUGULIN, F.FUGULIN,
    MA.MARTINS,
    G.CD_GLASGOW, G.GLASGOW
FROM ATENDIMENTO_PACIENTE_V APV
JOIN PH_OCUPACAO_RETROATIVA POR
    ON POR.NR_ATENDIMENTO = APV.NR_ATENDIMENTO
LEFT JOIN CTE_MEWS    M  ON M.NR_ATENDIMENTO  = APV.NR_ATENDIMENTO AND M.RN  = 1
LEFT JOIN CTE_BRADEN  B  ON B.NR_ATENDIMENTO  = APV.NR_ATENDIMENTO AND B.RN  = 1
LEFT JOIN CTE_MORSE   MO ON MO.NR_ATENDIMENTO = APV.NR_ATENDIMENTO AND MO.RN = 1
LEFT JOIN CTE_SAPS3   S  ON S.NR_ATENDIMENTO  = APV.NR_ATENDIMENTO AND S.RN  = 1
LEFT JOIN CTE_RASS    R  ON R.NR_ATENDIMENTO  = APV.NR_ATENDIMENTO AND R.RN  = 1
LEFT JOIN CTE_FUGULIN F  ON F.NR_ATENDIMENTO  = APV.NR_ATENDIMENTO AND F.RN  = 1
LEFT JOIN CTE_MARTINS MA ON MA.NR_ATENDIMENTO = APV.NR_ATENDIMENTO AND MA.RN = 1
LEFT JOIN CTE_GLASGOW G  ON G.NR_ATENDIMENTO  = APV.NR_ATENDIMENTO AND G.RN  = 1
WHERE POR.SITUACAO_LEITO = 'A'
  AND POR.STATUS_LEITO   = 'P'
  AND POR.DATA_REF >= TO_DATE(:DATA_INICIAL, 'dd/mm/yyyy')
  AND POR.DATA_REF  < TO_DATE(:DATA_FINAL,   'dd/mm/yyyy') + 1
/*{{FILTER_SETOR}}*/
GROUP BY
    POR.CD_SETOR_ATENDIMENTO,
    APV.CD_PESSOA_FISICA,
    APV.NR_ATENDIMENTO,
    POR.LEITO,
    POR.COMPLEMENTO,
    APV.DT_ENTRADA,
    POR.DATA_REF,
    M.CD_MEWS,   M.MEWS,
    B.CD_BRADEN, B.BRADEN,
    MO.CD_MORSE, MO.MORSE,
    S.CD_SAPSIII, S.SAP3,
    R.CD_RASS,   R.RASS,
    F.CD_FUGULIN, F.FUGULIN,
    MA.MARTINS,
    G.CD_GLASGOW, G.GLASGOW
ORDER BY
    POR.DATA_REF,
    SETOR,
    LEITO
