--04/08/2025  
--@IvanReis
SELECT
por.CD_SETOR_ATENDIMENTO ,
OBTER_DESC_SETOR_ATEND(por.CD_SETOR_ATENDIMENTO) AS SETOR,
POR.LEITO ||' '|| POR.COMPLEMENTO AS LEITO,
APV.NR_ATENDIMENTO,
OBTER_NOME_PACIENTE(APV.NR_ATENDIMENTO) AS PACIENTE,
-- TO_CHAR(APV.DT_ENTRADA,'dd/mm/yy hh24:mi') AS ENTRADA,
TO_CHAR(POR.DATA_REF,'dd/mm/yy') AS ENTRADA,
--MEWS (Otimizado: Código | Descrição)
(SELECT EM.QT_PONTUACAO || '|' || 
    CASE 
        WHEN QT_PONTUACAO BETWEEN 0 AND 4 THEN 'BAIXO' 
        WHEN QT_PONTUACAO BETWEEN 5 AND 6 THEN 'MEDIO' 
        WHEN QT_PONTUACAO BETWEEN 7 AND 12 THEN 'ALTO' 
    ELSE NULL END
  FROM ESCALA_MEWS EM, ATENDIMENTO_PACIENTE_V A
  WHERE A.NR_ATENDIMENTO = EM.NR_ATENDIMENTO
  AND A.DT_ALTA IS NULL
  AND A.NR_ATENDIMENTO = APV.NR_ATENDIMENTO
  AND EM.IE_SITUACAO = 'A'
  ORDER BY EM.DT_AVALIACAO DESC
  FETCH FIRST 1 ROWS ONLY
) AS RAW_MEWS,
--BRADEN (Otimizado: Código | Descrição)
(SELECT AEB.QT_PONTO || '|' || INITCAP(OBTER_RESULTADO_BRADEN(AEB.QT_PONTO))
  FROM  ATEND_ESCALA_BRADEN AEB
  WHERE   (NR_ATENDIMENTO = APV.NR_ATENDIMENTO)
  AND AEB.IE_SITUACAO = 'A'
  ORDER BY  1 DESC
  FETCH FIRST 1 ROWS ONLY
) AS RAW_BRADEN,                           
--MORSE (Otimizado: Código | Descrição)
(SELECT QT_PONTUACAO || '|' || INITCAP(OBTER_DESC_ESCALA_MORSE(QT_PONTUACAO))
  FROM  ESCALA_MORSE EMM
  WHERE EMM.NR_ATENDIMENTO = APV.NR_ATENDIMENTO
  AND EMM.IE_SITUACAO = 'A'
  ORDER BY  1 DESC
  FETCH FIRST 1 ROWS ONLY
) AS RAW_MORSE,
--SAPS3 (Otimizado: Código | Descrição)
(SELECT QT_PONTUACAO || '|' || QT_PONTUACAO||' / '||PR_RISCO||'%'
  FROM  ESCALA_SAPS3 SAPS3
  WHERE SAPS3.NR_ATENDIMENTO = APV.NR_ATENDIMENTO
  AND SAPS3.IE_SITUACAO = 'A'
  ORDER BY  1 DESC
  FETCH FIRST 1 ROWS ONLY
) AS RAW_SAPS3,                            
--RASS (Otimizado: Código | Descrição)
(SELECT IE_RASS || '|' || OBTER_VALOR_DOMINIO(2088, IE_RASS)
  FROM ESCALA_RICHMOND
  WHERE 1 = 1
  AND NR_ATENDIMENTO = APV.NR_ATENDIMENTO
  AND OBTER_SE_REG_LIB_ATENCAO(OBTER_PESSOA_ATENDIMENTO(NR_ATENDIMENTO, 'C'),CD_PROFISSIONAL,IE_NIVEL_ATENCAO,NM_USUARIO,374) = 'S'
  FETCH FIRST 1 ROWS ONLY
) RAW_RASS,
--FUGULIN (Otimizado: Código | Descrição)
(SELECT (SELECT DS_GRADACAO || '|' || 
    DECODE(
      DS_GRADACAO,
      'CM', 'Cuidados Mínimos',
      'CI', 'Cuidados Intermediários',
      'AD', 'Alta Dependência',
      'SI', 'Cuidados Semi Intensivos',
      'I', 'Cuidados Intensivos',
      DS_GRADACAO)                                       
    FROM GCA_GRADACAO 
    WHERE NR_SEQUENCIA = (
        SELECT NR_SEQ_GRADACAO 
        FROM GCA_ATENDIMENTO 
        WHERE NR_SEQUENCIA = 
            (SELECT MAX(NR_SEQUENCIA) 
                FROM GCA_ATENDIMENTO 
                WHERE NR_ATENDIMENTO = AP.NR_ATENDIMENTO 
                AND IE_SITUACAO = 'A' 
                AND TRUNC(DT_AVALIACAO) = TRUNC(GCAA.DT_AVALIACAO))))
  FROM ATENDIMENTO_PACIENTE AP
  INNER JOIN GCA_ATENDIMENTO GCAA ON GCAA.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
  INNER JOIN GCA_GRADACAO GCAG ON GCAG.NR_SEQUENCIA = GCAA.NR_SEQ_GRADACAO
  WHERE GCAA.IE_SITUACAO = 'A'
  AND AP.NR_ATENDIMENTO = APV.NR_ATENDIMENTO
  ORDER BY GCAA.DT_AVALIACAO DESC
  FETCH FIRST 1 ROWS ONLY
) AS RAW_FUGULIN,
--MARTINS (Mantido original pois já era otimizado/complexo)
(SELECT
  SUBSTR(OBTER_DESC_RESUL_SCORE_FLEX_2(EEI.QT_PONTOS,EEI.NR_SEQ_ESCALA),1,255)
  FROM ESCALA_EIF_II EEII
  INNER JOIN ESCALA_EIF_II EEI ON (EEI.NR_SEQUENCIA = EEII.NR_SEQUENCIA)
  INNER JOIN SCORE_AVALIACAO_RESULT SAR ON (EEII.NR_SEQUENCIA = SAR.NR_SEQ_AVALIACAO)
  INNER JOIN MED_ITEM_AVALIAR MIA ON (MIA.NR_SEQUENCIA = SAR.NR_SEQ_ITEM)
  INNER JOIN MED_TIPO_AVALIACAO MTA ON (MTA.NR_SEQUENCIA = MIA.NR_SEQ_TIPO)
  WHERE EEII.NR_ATENDIMENTO = APV.NR_ATENDIMENTO
  AND SAR.DS_RESULTADO IS NOT NULL
  AND EEII.DT_LIBERACAO IS NOT NULL
  AND UPPER(MTA.DS_TIPO) LIKE '%MARTINS%'
  AND EEII.IE_SITUACAO = 'A'
  GROUP BY EEII.DT_AVALIACAO, EEI.QT_PONTOS, EEI.NR_SEQ_ESCALA
  ORDER BY EEII.DT_AVALIACAO DESC
  FETCH FIRST 1 ROWS ONLY
) AS MARTINS,
--GLASGOW (Otimizado: Código | Descrição)
(SELECT  
  AEI.QT_GLASGOW || '|' || OBTER_RESULTADO_GLASGOW(AEI.QT_GLASGOW)
  FROM  ATEND_ESCALA_INDICE AEI
  WHERE   OBTER_SE_REG_LIB_ATENCAO(
  OBTER_PESSOA_ATENDIMENTO(
  AEI.NR_ATENDIMENTO,'C'), 
  AEI.CD_PESSOA_FISICA, 
  AEI.IE_NIVEL_ATENCAO, 
  AEI.NM_USUARIO, 374) = 'S'
  AND AEI.NR_ATENDIMENTO = APV.NR_ATENDIMENTO
  ORDER BY AEI.DT_AVALIACAO DESC
  FETCH FIRST 1 ROWS ONLY
) AS RAW_GLASGOW

FROM ATENDIMENTO_PACIENTE_V APV
JOIN PH_OCUPACAO_RETROATIVA POR ON ( POR.NR_ATENDIMENTO = APV.NR_ATENDIMENTO )
--=============================================== REGRAS DE NEGOCIO ===============================================
WHERE 1=1
AND   POR.SITUACAO_LEITO = 'A'
AND   POR.STATUS_LEITO = 'P'
-- Otimização& Evita o TRUNC() na coluna para permitir o uso de índices.
AND POR.DATA_REF >= TO_DATE(:DATA_INICIAL, 'dd/mm/yyyy') 
AND POR.DATA_REF < TO_DATE(:DATA_FINAL, 'dd/mm/yyyy') + 1
-- AND TRUNC(POR.DATA_REF) BETWEEN &DATA_INICIAL AND &DATA_FINAL
/*{{FILTER_SETOR}}*/
--AND APV.DT_ALTA IS NULL

GROUP BY 
por.CD_SETOR_ATENDIMENTO,
APV.CD_PESSOA_FISICA,
APV.NR_ATENDIMENTO,
POR.LEITO,
POR.COMPLEMENTO, APV.DT_ENTRADA,POR.DATA_REF

ORDER BY 
POR.DATA_REF,
OBTER_DESC_SETOR_ATEND(por.CD_SETOR_ATENDIMENTO),
POR.LEITO ||' '|| POR.COMPLEMENTO
--OBTER_NOME_PF(APV.CD_PESSOA_FISICA)