--16/12/2024
--@PLima

-- HSF - RESULTADOS EXAMES COM INTERVALOS DE ALERTA
SELECT A.DATA_REF DATA_REFERENCIA,    
       A.SITUACAO_LEITO,
       A.STATUS_LEITO_DESCR STATUS_LEITO,  
       A.CD_SETOR_ATENDIMENTO,
       A.SEOTR_ATENDIMENTO SETOR,
       A.LEITO ||' '|| A.COMPLEMENTO DS_LEITO,       
       A.NR_ATENDIMENTO,
       OBTER_NOME_PACIENTE(A.NR_ATENDIMENTO) AS PACIENTE,
  ---- MEWS
  (SELECT 
    EM.QT_PONTUACAO AS CLASSIFICACAO
    FROM ESCALA_MEWS EM, ATENDIMENTO_PACIENTE_V A
    WHERE A.NR_ATENDIMENTO = EM.NR_ATENDIMENTO
    AND A.DT_ALTA IS NULL
    AND A.NR_ATENDIMENTO = A.NR_ATENDIMENTO
    AND EM.IE_SITUACAO = 'A'
    ORDER BY EM.DT_AVALIACAO DESC
    FETCH FIRST 1 ROWS ONLY
  ) AS CD_MEWS,
  (SELECT
    EM.QT_PONTUACAO || ' - ' ||
    CASE
      WHEN EM.QT_PONTUACAO BETWEEN 0 AND 4 THEN 'BAIXO'
      WHEN EM.QT_PONTUACAO BETWEEN 5 AND 6 THEN 'MEDIO'
      WHEN EM.QT_PONTUACAO BETWEEN 7 AND 12 THEN 'ALTO'
      ELSE NULL
    END AS CLASSIFICACAO
    FROM ESCALA_MEWS EM, ATENDIMENTO_PACIENTE_V A
    WHERE A.NR_ATENDIMENTO = EM.NR_ATENDIMENTO
    AND A.DT_ALTA IS NULL
    AND A.NR_ATENDIMENTO = A.NR_ATENDIMENTO
    AND EM.IE_SITUACAO = 'A'
    ORDER BY EM.DT_AVALIACAO DESC
    FETCH FIRST 1 ROWS ONLY
  ) AS DS_MEWS,
  ---- BRADEN
  (SELECT  
    AEB.QT_PONTO
    FROM  ATEND_ESCALA_BRADEN AEB
    WHERE   (NR_ATENDIMENTO = A.NR_ATENDIMENTO)
    AND AEB.IE_SITUACAO = 'A'
    ORDER BY  1 DESC
    FETCH FIRST 1 ROWS ONLY
  ) AS CD_BRADEN,
  (SELECT  
    INITCAP(OBTER_RESULTADO_BRADEN(AEB.QT_PONTO))
    FROM  ATEND_ESCALA_BRADEN AEB
    WHERE   (NR_ATENDIMENTO = A.NR_ATENDIMENTO)
    AND AEB.IE_SITUACAO = 'A'
    ORDER BY  1 DESC
    FETCH FIRST 1 ROWS ONLY
  ) AS DS_BRADEN,
  --MORSE
  (SELECT  
    QT_PONTUACAO
    FROM  ESCALA_MORSE EMM
    WHERE EMM.NR_ATENDIMENTO = A.NR_ATENDIMENTO
    AND EMM.IE_SITUACAO = 'A'
    ORDER BY  1 DESC
    FETCH FIRST 1 ROWS ONLY
  ) AS CD_MORSE,
  (SELECT  
    INITCAP(OBTER_DESC_ESCALA_MORSE(QT_PONTUACAO))
    FROM  ESCALA_MORSE EMM
    WHERE EMM.NR_ATENDIMENTO = A.NR_ATENDIMENTO
    AND EMM.IE_SITUACAO = 'A'
    ORDER BY  1 DESC
    FETCH FIRST 1 ROWS ONLY
  ) AS DS_MORSE,
  --SAPS3
  (SELECT  
    QT_PONTUACAO
    FROM  ESCALA_SAPS3 SAPS3
    WHERE SAPS3.NR_ATENDIMENTO = A.NR_ATENDIMENTO
    AND SAPS3.IE_SITUACAO = 'A'
    ORDER BY  1 DESC
    FETCH FIRST 1 ROWS ONLY
  ) AS CD_SAPSIII,
  (SELECT  
    QT_PONTUACAO||' / '||PR_RISCO||'%'
    FROM  ESCALA_SAPS3 SAPS3
    WHERE SAPS3.NR_ATENDIMENTO = A.NR_ATENDIMENTO
    AND SAPS3.IE_SITUACAO = 'A'
    ORDER BY  1 DESC
    FETCH FIRST 1 ROWS ONLY
  ) AS DS_SAPSIII,
  --RASS
  (SELECT
    IE_RASS
    FROM ESCALA_RICHMOND
    WHERE 1 = 1
    AND NR_ATENDIMENTO = A.NR_ATENDIMENTO
    AND OBTER_SE_REG_LIB_ATENCAO(OBTER_PESSOA_ATENDIMENTO(NR_ATENDIMENTO, 'C'),CD_PROFISSIONAL,IE_NIVEL_ATENCAO,NM_USUARIO,374) = 'S'
    FETCH FIRST 1 ROWS ONLY
  ) CD_RASS,
  (SELECT
    OBTER_VALOR_DOMINIO(2088, IE_RASS)AS DS_AGITACAO_SEDACAO
    FROM ESCALA_RICHMOND
    WHERE 1 = 1
    AND NR_ATENDIMENTO = A.NR_ATENDIMENTO
    AND OBTER_SE_REG_LIB_ATENCAO(OBTER_PESSOA_ATENDIMENTO(NR_ATENDIMENTO, 'C'),CD_PROFISSIONAL,IE_NIVEL_ATENCAO,NM_USUARIO,374) = 'S'
    FETCH FIRST 1 ROWS ONLY
  ) DS_RASS,
  --FUGULIN
  (SELECT 
    (SELECT 
    DS_GRADACAO                                        
    FROM GCA_GRADACAO 
    WHERE NR_SEQUENCIA = (SELECT NR_SEQ_GRADACAO 
                   FROM GCA_ATENDIMENTO 
                   WHERE NR_SEQUENCIA = 
                   (SELECT MAX(NR_SEQUENCIA) 
                  FROM GCA_ATENDIMENTO 
                  WHERE NR_ATENDIMENTO = AP.NR_ATENDIMENTO 
                  AND IE_SITUACAO = 'A' 
                  AND TRUNC(DT_AVALIACAO) = TRUNC(GCAA.DT_AVALIACAO)))
    )
  FROM ATENDIMENTO_PACIENTE AP
  INNER JOIN GCA_ATENDIMENTO GCAA ON GCAA.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
  INNER JOIN GCA_GRADACAO GCAG ON GCAG.NR_SEQUENCIA = GCAA.NR_SEQ_GRADACAO
  WHERE GCAA.IE_SITUACAO = 'A'
  AND AP.NR_ATENDIMENTO = A.NR_ATENDIMENTO
  ORDER BY GCAA.DT_AVALIACAO DESC
  FETCH FIRST 1 ROWS ONLY
  ) AS CD_FUGULIN,
  (SELECT 
    (SELECT   
    DECODE(
    DS_GRADACAO,
    'CM', 'Cuidados Mínimos',
    'CI', 'Cuidados Intermediários',
    'AD', 'Alta Dependência',
    'SI', 'Cuidados Semi Intensivos',
    'I', 'Cuidados Intensivos',
    DS_GRADACAO)                                        
    FROM GCA_GRADACAO 
    WHERE NR_SEQUENCIA = (SELECT NR_SEQ_GRADACAO 
                   FROM GCA_ATENDIMENTO 
                   WHERE NR_SEQUENCIA = 
                   (SELECT MAX(NR_SEQUENCIA) 
                  FROM GCA_ATENDIMENTO 
                  WHERE NR_ATENDIMENTO = AP.NR_ATENDIMENTO 
                  AND IE_SITUACAO = 'A' 
                  AND TRUNC(DT_AVALIACAO) = TRUNC(GCAA.DT_AVALIACAO)))
    )
  FROM ATENDIMENTO_PACIENTE AP
  INNER JOIN GCA_ATENDIMENTO GCAA ON GCAA.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
  INNER JOIN GCA_GRADACAO GCAG ON GCAG.NR_SEQUENCIA = GCAA.NR_SEQ_GRADACAO
  WHERE GCAA.IE_SITUACAO = 'A'
  AND AP.NR_ATENDIMENTO = A.NR_ATENDIMENTO
  ORDER BY GCAA.DT_AVALIACAO DESC
  FETCH FIRST 1 ROWS ONLY
  ) AS FUGULIN, 
  --MARTINS
  (SELECT
    SUBSTR(OBTER_DESC_RESUL_SCORE_FLEX_2(EEI.QT_PONTOS,EEI.NR_SEQ_ESCALA),1,255)
    FROM ESCALA_EIF_II EEII
    INNER JOIN ESCALA_EIF_II EEI ON (EEI.NR_SEQUENCIA = EEII.NR_SEQUENCIA)
    INNER JOIN SCORE_AVALIACAO_RESULT SAR ON (EEII.NR_SEQUENCIA = SAR.NR_SEQ_AVALIACAO)
    INNER JOIN MED_ITEM_AVALIAR MIA ON (MIA.NR_SEQUENCIA = SAR.NR_SEQ_ITEM)
    INNER JOIN MED_TIPO_AVALIACAO MTA ON (MTA.NR_SEQUENCIA = MIA.NR_SEQ_TIPO)
    WHERE EEII.NR_ATENDIMENTO = A.NR_ATENDIMENTO
    AND SAR.DS_RESULTADO IS NOT NULL
    AND EEII.DT_LIBERACAO IS NOT NULL
    AND UPPER(MTA.DS_TIPO) LIKE '%MARTINS%'
    AND EEII.IE_SITUACAO = 'A'
    GROUP BY EEII.DT_AVALIACAO, EEI.QT_PONTOS, EEI.NR_SEQ_ESCALA, EEII.NR_ATENDIMENTO 
    ORDER BY EEII.DT_AVALIACAO DESC
    FETCH FIRST 1 ROWS ONLY
  ) AS MARTINS,
  ---- GLASGOW
  (SELECT  
    AEI.QT_GLASGOW
    FROM  ATEND_ESCALA_INDICE AEI
    WHERE OBTER_SE_REG_LIB_ATENCAO(OBTER_PESSOA_ATENDIMENTO(AEI.NR_ATENDIMENTO,'C'), AEI.CD_PESSOA_FISICA,AEI.IE_NIVEL_ATENCAO, AEI.NM_USUARIO, 374) = 'S'
    AND   AEI.NR_ATENDIMENTO = A.NR_ATENDIMENTO
    ORDER BY AEI.DT_AVALIACAO DESC
    FETCH FIRST 1 ROWS ONLY
  ) AS CD_GLASGOW,
  (SELECT  
    OBTER_RESULTADO_GLASGOW(AEI.QT_GLASGOW)
    FROM  ATEND_ESCALA_INDICE AEI
    WHERE OBTER_SE_REG_LIB_ATENCAO(OBTER_PESSOA_ATENDIMENTO(AEI.NR_ATENDIMENTO,'C'), AEI.CD_PESSOA_FISICA,AEI.IE_NIVEL_ATENCAO, AEI.NM_USUARIO, 374) = 'S'
    AND   AEI.NR_ATENDIMENTO = A.NR_ATENDIMENTO
    ORDER BY AEI.DT_AVALIACAO DESC
    FETCH FIRST 1 ROWS ONLY
  ) AS DS_GLASGOW

FROM PH_OCUPACAO_RETROATIVA A
WHERE 1=1  
AND A.SITUACAO_LEITO = 'A'
AND A.STATUS_LEITO   = 'P'  
AND TRUNC(A.DATA_REF) BETWEEN TO_DATE(:DATA_INICIAL, 'dd/mm/yyyy') AND TO_DATE(:DATA_FINAL, 'dd/mm/yyyy')
--AND A.CD_SETOR_ATENDIMENTO IN (58,59,60,61,63,236)
AND ((A.CD_SETOR_ATENDIMENTO = :CD_SETOR_P) OR (:CD_SETOR_P = '0'))

ORDER BY DATA_REFERENCIA ,SETOR, PACIENTE

