SELECT
  TRUNC(c.DT_INICIO_REAL) AS DT_CIRURGIA,
  CASE
    WHEN c.IE_CARATER_CIRURGIA = 'E' THEN 'Eletiva'
    WHEN c.IE_CARATER_CIRURGIA IN ('M','U') THEN 'Urgência / Emergência'
    ELSE 'OUTROS'
  END AS GRUPO_CARATER,
  /*Cálculo para porte I, II, III e IV*/
  COUNT(CASE WHEN c.NR_MIN_DURACAO_REAL <= 120 THEN 1 END)  AS QT_PORTE_1,   -- 0 a 2 horas
  COUNT(CASE WHEN c.NR_MIN_DURACAO_REAL > 120 AND c.NR_MIN_DURACAO_REAL <= 240 THEN 1 END) AS QT_PORTE_2,   -- 2 a 4 horas
  COUNT(CASE WHEN c.NR_MIN_DURACAO_REAL > 240 AND c.NR_MIN_DURACAO_REAL <= 360 THEN 1 END) AS QT_PORTE_3,   -- 4 a 6 horas
  COUNT(CASE WHEN c.NR_MIN_DURACAO_REAL > 360 THEN 1 END) AS QT_PORTE_4,   -- Acima de 6 horas
  COUNT(c.NR_MIN_DURACAO_REAL) AS QT_TOTAL,
  /* percentuais dentro do grupo (E ou M+U) */
  ROUND(100 * COUNT(CASE WHEN c.NR_MIN_DURACAO_REAL <= 120 THEN 1 END) / NULLIF(COUNT(*),0), 1) AS PCT_PORTE_1,
  ROUND(100 * COUNT(CASE WHEN c.NR_MIN_DURACAO_REAL > 120 AND c.NR_MIN_DURACAO_REAL <= 240 THEN 1 END) / NULLIF(COUNT(*),0), 1) AS PCT_PORTE_2,
  ROUND(100 * COUNT(CASE WHEN c.NR_MIN_DURACAO_REAL > 240 AND c.NR_MIN_DURACAO_REAL <= 360 THEN 1 END) / NULLIF(COUNT(*),0), 1) AS PCT_PORTE_3,
  ROUND(100 * COUNT(CASE WHEN c.NR_MIN_DURACAO_REAL > 360 THEN 1 END) / NULLIF(COUNT(*),0), 1) AS PCT_PORTE_4
FROM CIRURGIA_v c
WHERE TRUNC(c.DT_INICIO_REAL) BETWEEN :DATA_INICIAL AND :DATA_FINAL
AND CD_SETOR_ATENDIMENTO <> 47 -- H - Hemodinamica
GROUP BY
  TRUNC(c.DT_INICIO_REAL),
  CASE
    WHEN c.IE_CARATER_CIRURGIA = 'E' THEN 'Eletiva'
    WHEN c.IE_CARATER_CIRURGIA IN ('M','U') THEN 'Urgência / Emergência'
    ELSE 'OUTROS'
  END
ORDER BY DT_CIRURGIA, GRUPO_CARATER